version: '2.2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: forge
  web:
    image: gleandroj/laravel
    ports:
      - "80:80"
    volumes:
      - .:/home/deploy/app:Z
    depends_on:
      - db